### ISSUE TITLE
RavePayService.swift Fix 

### ISSUE THREAD

**Issue by drakeson** [Flutterwave/RaveSDK#1]
If you are having errors with RavePayService.swift when you upgrade your Alamofire to 5 here is the solution
https://gist.github.com/drakeson/0f13fc3796faea860f293845ff6a3ca6

<img width="866" alt="Screen Shot 2020-04-21 at 3 35 11 AM" src="https://user-images.githubusercontent.com/17096840/79812280-213eb900-8381-11ea-9034-9037786065f0.png">

**Comment by corneliusyaovi** [comment]
Hello @drakeson, Thanks for raising this issue. 

Kindly note that the issue has been fixed.
