### ISSUE TITLE
GH Mobile Money stucked on loading screen

### ISSUE THREAD

**Issue by MohammedBashiru** [Flutterwave/RaveSDK#14]
Hello,
When initiating **Ghana mobile money payment** it get stuck after selecting network type and mobile number.
Momo auth get received via sms and whatsapp. Except the loading does not go away for you to enter payment auth code.

Please can you look into this issue ASAP?
Thank you.

**Comment by MohammedBashiru** [comment]
I looked into the source code and realized 
**mobileMobileCallbacks** didn't have **chargeWebAuth**  functionality in **RaveMobileMoneyClient.swift**

Also it would be great if after payment the modal closes.
Currently it stays still.

**Comment by texyz** [comment]
Hi @MohammedBashiru thank you for reaching out to us. Please what version of the SDK are you using?

**Comment by MohammedBashiru** [comment]
Hello @texyz, thank you for your response.
I am using version 2.2.0

**Comment by MohammedBashiru** [comment]
@texyz Please can we get fix ET today ?

**Comment by texyz** [comment]
Hi @MohammedBashiru can you please send us a mail at developers@flutterwavego.com to have a closer look at this issue.

**Comment by 154010** [comment]
I also facing the same issue now,can anyone tell me the solution for this issue??

**Comment by texyz** [comment]
@154010  Please send us a mail at developers@flutterwavego.com

**Comment by AshokRadadiya** [comment]
I also facing the same issue now,can anyone tell me the solution for this issue?

Mobile money not working for Ghana currency... 

Please update new iOS RaveSDK version....

**Comment by texyz** [comment]
@AshokRadadiya @154010 This has been resolved, please update your pod. Thank you

**Comment by AshokRadadiya** [comment]
Thanks for updating iOS RaveSDK 2.2.2.

I make payment using mobile money with GHS currency code. The
tranasctionSuccessful called
but Status display failed..

We will find some small bugs like when you make payment using mobile money
when loading dialog not spinning.

Also we are not set Recurring payment plans method...

I am waiting for your reply!

Thanks!

**Comment by AshokRadadiya** [comment]
Hi flutterwave team,

I have attached video.

Please check that properly, when payment is successful on iOS then
call tranasctionSuccessful method
call but *status:failed *return*. *

If payment *status:failed then why not call *tranasctionFailed method.

We are waiting for your reply...

Thank you!

**Comment by texyz** [comment]
Hi @AshokRadadiya apologies for that experience, please can you share the video or the link to the video again, can't find it in the thread.

**Comment by 154010** [comment]
I am also facing the same issue while using mobile money,the paymet has goes to the cancelled status in dash board.
I dont know why it is happen??

**Comment by texyz** [comment]
I will proceed to close this issue and mark it as resolved.
