### ISSUE TITLE
In Card Payment

### ISSUE THREAD

**Issue by 154010** [Flutterwave/RaveSDK#16]

**Comment by 154010** [comment]
While using card payment
On transaction success,different structures i got 

1)While using saved card
In response data "id" is given in the response dict directly, flw_ref is also coming

2)While using on enter card number
for this test card 
Card number: 5531 8866 5214 2950
cvv: 564
Expiry: 09/32
Pin: 3310
OTP: 12345
In response data "id" is given inside the "tx" in the response dict, flw_ref is also coming

3)While using on enter card number
for this test card 
Card number: 4187 4274 1556 4246
cvv: 828
Expiry: 09/32
Pin: 3310
OTP: 12345
In response data is coming **nil** , flw_ref is only coming

4)for ghana mobile money
In response data "id" is given in the response dict directly, flw_ref is **nil** not coming in delegate method
only inside the response dict

How Can I Handle those??
BackEnd Team is asked for id,but i cant take id all the time
Rave SDK 2.2.2 iOS
Please Assist,ThankYou

**Comment by texyz** [comment]
@154010 I reproduced case 3  and 4 **data.id** was returned as `**id = 1946755**` for case 3 and **`flw_ref`** was also returned for case 4 as `**flwm3s4m0c1614941281534**` . Please try again!

You can also upgrade to [2.2.2](https://github.com/Flutterwave/RaveSDK/releases/tag/2.2.2) if you are not using the latest version.
