### ISSUE TITLE
touch error

### ISSUE THREAD

**Issue by AmMuhammadAhmad** [Flutterwave/RaveSDK#19]
Hi, I have to face an error after I install the pod then copy-paste code into button click.i cannot click on any text field not working.clicking not working.

**Comment by Ochornma** [comment]
How were you able to resolve this issue

**Comment by heywhy** [comment]
I'm facing the same issue. Who is able to resolve this?

**Comment by texyz** [comment]
@Ahmadabad @Ochornma @heywhy Sincere apologies for the late response, please what version of the SDK are you using?
