### ISSUE TITLE
Bank Payment Response

### ISSUE THREAD

**Issue by AdieOlami** [Flutterwave/RaveSDK#2]
Hi, I integrated this SDK and I have an issue with a success response which contained failure status.

I would just attach an image to satisfy this check.
<img width="310" alt="Screen Shot 2020-07-11 at 10 57 20 AM" src="https://user-images.githubusercontent.com/22158320/87221653-8b09a600-c365-11ea-8234-e6f834a12c2e.png">

so the response is success but still showing failure values in the data object.

**Comment by corneliusyaovi** [comment]
Hello @AdieOlami ,

Please note that `"status": "successful"` refers to the status of the HTTP connection. It is only sent when a request has been processed and the server sends back a response.

The actual status of the transaction is contained in the data object in the response.

I hope this clarifies your enquiry.

Regards,
