### ISSUE TITLE
Response Data for Card and Bank Account returns nil

### ISSUE THREAD

**Issue by SOGAPPS** [Flutterwave/RaveSDK#22]
The "responseData" returns nil for function "`func tranasctionSuccessful(flwRef: String?, responseData: [String : Any]?)`".

We require the "**txRef**" to verify our transaction using "Verify transaction" API v2. 
**Note**: We intend to upgrade to "Verify transaction" API v3. On v3 only "data.id" is required to verify transaction.

Q1. Do we need to "Verify transaction" for both "Card" and "Bank Account" Transactions?
Q2. How do we verify transaction if iOS "responseData" returns nil
Q3. `let config = RaveConfig.sharedConfig()
        config.transcationRef = "ref" `. Is "transcationRef" == the returned `responseData!["tx"]["txRef"]`?

**Comment by texyz** [comment]
@SOGAPPS Apologies about that experience, can you please confirm the version of the SDK you are using

Q1. Yes you are required to verify all transactions
Q2. Please confirm the version of the SDK you are using, for our v3 API and SDKS, data.id is required to verify all transactions (https://api.flutterwave.com/v3/transactions/{id}/verify). This is the transaction unique identifier. It is returned in the initiate transaction call as data.id
Q3. Please provide more context to question 3

**Comment by SOGAPPS** [comment]
@texyz thanks for the follow-up.

SDK Version: On iOS we are using "RaveSDK (2.3.3)". FYI - Issue also appears in v2.2.1

Q3. In summary can we use the same reference required for building the `RaveConfig.sharedConfig()` to verity transaction. 
A temporary solution to "responseData" data returning nil.  "Verify transaction" API v2 needs  the "txRef".

**Comment by SOGAPPS** [comment]
@texyz Thanks, the "responseData" now returns data.
Using SDK Version: "RaveSDK (2.3.3)"

**Comment by binemugha** [comment]
Response Data for VISA card returns nil from the function:

func tranasctionSuccessful(flwRef: String?, responseData: [String : Any]?){
        print(responseData?.description ?? "Nothing here")
}

"Nothing here" gets printed whenever I use a test VISA card with the following details

Card number: 4187 4274 1556 4246
cvv: 828
Expiry: 09/32
Pin: 3310
OTP: 12345
