### ISSUE TITLE
An error occurred while attempting to decrepit some parameters  

### ISSUE THREAD

**Issue by FTKamlesh** [Flutterwave/RaveSDK#4]
Hi, Just use RaveSDK for iOS. I go though rave doc and got successfully adding card details. But I got error while click on Pay. 
I seen first prompt that was charges I attached screen shot [Please Check](https://www.dropbox.com/s/i350kqpq5dx1xbh/Charge.png?dl=0) and then I clicked on Proceed I got error I attached screen shot [Please check](https://www.dropbox.com/s/mn60vqzcvg98le9/ERROR.png?dl=0)

Here is my code

```
let raveMgr = RavePayManager()
           raveMgr.email = "test@example.com" //Customer's email address
           raveMgr.amount = "25" // Amount
           raveMgr.transcationRef = "Unique-Transaction-ref" //Unique transaction reference
           raveMgr.currencyCode = "KES"
           raveMgr.delegate = self
           raveMgr.narration = "narration"
           raveMgr.supportedPaymentMethods = [.card, .account]
        
//           raveMrg.supportedPaymentMethods = [.card,.account] // Choose supported payment channel allowed
           //Set your recurring payment ID, Only set this if you are enabling recurring payments
           //raveMgr.paymentPlan = <PAYMENT PLAN ID>

           raveMgr.show(withController:self)
```
I entered this card details

5377 2836 4507 7450
cvv 789
Expiry: 09/21
Pin 3310

Please suggest me if I am doing wrong. Thanks

**Comment by corneliusyaovi** [comment]
@FTKamlesh please confirm if test keys are used and isStaging is set to true.

**Comment by FTKamlesh** [comment]
Yes we are using test keys and isStaging is set to true
